services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  db-backup:
    image: fradelg/mysql-cron-backup
    container_name: mariadb_backup
    depends_on:
      - mariadb
    volumes:
      - ./db_backups:/backup
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DATABASE}
      - CRON_TIME=0 0 * * *
      - MYSQL_HOST=${MARIADB_HOST}
      - MYSQL_PORT=${MARIADB_PORT}
      - TIMEOUT=30s
      - INIT_BACKUP=1
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network

  read-spring-app:
    container_name: read-spring-app
    image: read-spring-app:latest
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      mariadb:
        condition: service_started

volumes:
  mariadb_data:

networks:
  app_network:
