apiVersion: v1
kind: ConfigMap
metadata:
  name: create-microservice-config
  namespace: movies-app
data:
  SERVER_PORT: "5000"
  MARIADB_HOST: "mariadb-service"
  MARIADB_PORT: "3306"
  MYSQL_DATABASE: "movies_db"
