apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-microservice-deployment
  namespace: movies-app
  labels:
    app: delete-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delete-microservice
  template:
    metadata:
      labels:
        app: delete-microservice
    spec:
      containers:
      - name: delete-microservice
        image: vargascardona/k8s-capstone-delete:latest
        ports:
        - containerPort: 5003
        env:
        - name: SERVER_PORT
          value: "5003"
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef:
              name: create-microservice-config
              key: MARIADB_HOST
        - name: MARIADB_PORT
          valueFrom:
            configMapKeyRef:
              name: create-microservice-config
              key: MARIADB_PORT
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: create-microservice-config
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

