apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: movies-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/mariadb
