apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-microservice-deployment
  namespace: movies-app
  labels:
    app: update-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: update-microservice
  template:
    metadata:
      labels:
        app: update-microservice
    spec:
      containers:
      - name: update-microservice
        image: vargascardona/k8s-capstone-update:latest
        ports:
        - containerPort: 5002
        env:
        - name: SERVER_PORT
          value: "5002"
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef:
              name: create-microservice-config
              key: MARIADB_HOST
        - name: MARIADB_PORT
          valueFrom:
            configMapKeyRef:
              name: create-microservice-config
              key: MARIADB_PORT
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: create-microservice-config
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

