apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  namespace: movies-app
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/backups

