apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup-cronjob
  namespace: movies-app
spec:
  schedule: "0 2 * * *"  # Ejecutar todos los días a las 2:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mariadb-backup
            image: mariadb:latest
            command:
            - /bin/bash
            - -c
            - |
              DATE=$(date +%Y%m%d_%H%M%S)
              BACKUP_FILE="/backup/movies_db_backup_$DATE.sql"
              mysqldump -h mariadb-service -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE > $BACKUP_FILE
              echo "Backup completed: $BACKUP_FILE"
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "movies_db"
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure
